import React from 'react';
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Font,
  renderToBuffer,
} from '@react-pdf/renderer';
import type { Brief } from '@/lib/schemas/brief';
import type { ConceptBrief } from '@/lib/schemas/concept-brief';
import type { StyleReport } from '@/lib/schemas/style-report';
import type { PromptDeck } from '@/lib/schemas/prompt-deck';
import type { AngleProposalDoc } from '@/lib/schemas/angle';

Font.register({
  family: 'Inter',
  fonts: [
    { src: 'https://rsms.me/inter/font-files/InterVariable.ttf' },
  ],
});

const styles = StyleSheet.create({
  page: { padding: 36, fontFamily: 'Helvetica', fontSize: 9.5, lineHeight: 1.5, color: '#1f1f1f' },
  header: {
    fontSize: 7,
    color: '#888',
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginBottom: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  h1: { fontSize: 24, fontWeight: 700, marginBottom: 12, color: '#0a0a0a' },
  h2: { fontSize: 14, fontWeight: 700, marginTop: 18, marginBottom: 8, color: '#0a0a0a' },
  h3: { fontSize: 11, fontWeight: 700, marginTop: 12, marginBottom: 4, color: '#0a0a0a' },
  lede: { fontSize: 11, lineHeight: 1.45, color: '#3a3a3a', marginBottom: 12 },
  body: { fontSize: 9.5, lineHeight: 1.5, marginBottom: 6 },
  small: { fontSize: 8, color: '#666', lineHeight: 1.4 },
  rule: { borderBottomWidth: 0.5, borderBottomColor: '#e0e0e0', marginVertical: 10 },
  fieldGrid: { flexDirection: 'row', flexWrap: 'wrap', marginBottom: 6 },
  fieldKey: { fontSize: 7.5, color: '#888', textTransform: 'uppercase', letterSpacing: 1, marginBottom: 2 },
  fieldVal: { fontSize: 9.5, marginBottom: 6 },
  swatchRow: { flexDirection: 'row', marginTop: 4, marginBottom: 4 },
  swatch: { width: 18, height: 18, marginRight: 4, borderRadius: 2 },
  code: { fontFamily: 'Courier', fontSize: 8, backgroundColor: '#f3f3f1', padding: 6, marginVertical: 4, lineHeight: 1.4 },
  card: {
    borderWidth: 0.5,
    borderColor: '#d8d8d6',
    borderRadius: 4,
    padding: 10,
    marginBottom: 8,
  },
  cardHead: { fontSize: 10, fontWeight: 700, marginBottom: 2 },
  cardDesc: { fontSize: 8, color: '#666', marginBottom: 6 },
  tag: {
    fontSize: 7,
    color: '#666',
    paddingHorizontal: 4,
    paddingVertical: 1,
    borderRadius: 2,
    backgroundColor: '#f0f0ee',
    alignSelf: 'flex-start',
  },
  pageNumber: {
    position: 'absolute',
    bottom: 18,
    right: 36,
    fontSize: 7,
    color: '#888',
    letterSpacing: 1,
  },
  footerLeft: {
    position: 'absolute',
    bottom: 18,
    left: 36,
    fontSize: 7,
    color: '#888',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
});

function PageHeader({ subtitle }: { subtitle?: string }) {
  return (
    <View style={styles.header} fixed>
      <Text>Confluencr Creative Cockpit{subtitle ? ` · ${subtitle}` : ''}</Text>
      <Text>Test Run Output</Text>
    </View>
  );
}

function PageFooter() {
  return (
    <>
      <Text style={styles.footerLeft} fixed>
        Confluencr Creative Cockpit
      </Text>
      <Text style={styles.pageNumber} fixed render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`} />
    </>
  );
}

export async function renderTestRunPdf(args: {
  brief: Brief;
  style: StyleReport | null;
  angles: AngleProposalDoc | null;
  concepts: ConceptBrief[];
  deck: PromptDeck | null;
}): Promise<Buffer> {
  const { brief, style, angles, concepts, deck } = args;
  const angleNameByConceptId: Record<string, string> = {};
  for (const c of concepts) {
    const angle = angles?.angles.find((a) => a.id === c.angleId);
    if (angle) angleNameByConceptId[c._id] = angle.name;
  }

  return renderToBuffer(
    <Document>
      {/* Cover */}
      <Page size="A4" style={styles.page}>
        <PageHeader />
        <Text style={styles.h1}>{brief.product.name || 'Untitled product'}</Text>
        <Text style={styles.lede}>{brief.product.oneLiner}</Text>
        <View style={styles.rule} />
        <Text style={styles.body}>Three on-brand image concept briefs, plus an execution-ready prompt deck.</Text>
        <Text style={styles.small}>Generated by the Confluencr Creative Cockpit · {new Date().toISOString().slice(0, 10)}</Text>
        <PageFooter />
      </Page>

      {/* Brief */}
      <Page size="A4" style={styles.page}>
        <PageHeader subtitle="Brand brief" />
        <Text style={styles.h2}>Brand brief</Text>

        <Text style={styles.fieldKey}>Audience</Text>
        <Text style={styles.fieldVal}>{brief.audience.description || '(blank)'}</Text>

        {brief.audience.insight && (
          <>
            <Text style={styles.fieldKey}>Insight</Text>
            <Text style={styles.fieldVal}>{brief.audience.insight}</Text>
          </>
        )}

        <Text style={styles.fieldKey}>Single-minded proposition</Text>
        <Text style={styles.fieldVal}>{brief.strategy.smp || '(blank)'}</Text>

        {brief.strategy.rtbs.length > 0 && (
          <>
            <Text style={styles.fieldKey}>Reasons to believe</Text>
            <Text style={styles.fieldVal}>{brief.strategy.rtbs.join(' · ')}</Text>
          </>
        )}

        {brief.brand.palette.length > 0 && (
          <>
            <Text style={styles.fieldKey}>Brand palette</Text>
            <View style={styles.swatchRow}>
              {brief.brand.palette.map((p, i) => (
                <View key={i} style={[styles.swatch, { backgroundColor: p.hex }]} />
              ))}
            </View>
            <Text style={styles.fieldVal}>
              {brief.brand.palette.map((p) => `${p.hex} (${p.role}, ${Math.round(p.ratio * 100)}%)`).join(' · ')}
            </Text>
          </>
        )}

        {brief.brand.voiceOpposites.length > 0 && (
          <>
            <Text style={styles.fieldKey}>Voice</Text>
            <Text style={styles.fieldVal}>
              {brief.brand.voiceOpposites.map((v) => `${v.x} NOT ${v.y}`).join(' · ')}
            </Text>
          </>
        )}

        {brief.references.inputs.length > 0 && (
          <>
            <Text style={styles.fieldKey}>Competitor references</Text>
            <Text style={styles.fieldVal}>
              {brief.references.inputs.map((r) => `[${r.kind}] ${r.value}`).join('\n')}
            </Text>
          </>
        )}

        {brief.references.doNotInclude.length > 0 && (
          <>
            <Text style={styles.fieldKey}>Do-not-include</Text>
            <Text style={styles.fieldVal}>{brief.references.doNotInclude.join(' · ')}</Text>
          </>
        )}

        <Text style={styles.fieldKey}>Surfaces</Text>
        <Text style={styles.fieldVal}>{brief.surfaces.aspectRatios.join(' · ')}</Text>

        <PageFooter />
      </Page>

      {/* Style Report */}
      {style && (
        <Page size="A4" style={styles.page}>
          <PageHeader subtitle="Competitor style report" />
          <Text style={styles.h2}>Competitor style report</Text>

          <Text style={styles.fieldKey}>Extracted palette</Text>
          <View style={styles.swatchRow}>
            {style.palette.map((p, i) => (
              <View key={i} style={[styles.swatch, { backgroundColor: p.hex }]} />
            ))}
          </View>
          <Text style={styles.fieldVal}>
            {style.palette.map((p) => `${p.hex} (${p.role}, ${Math.round(p.ratio * 100)}%)`).join(' · ')}
          </Text>

          <Text style={styles.fieldKey}>Lighting</Text>
          <Text style={styles.fieldVal}>{style.lighting}</Text>

          <Text style={styles.fieldKey}>Composition</Text>
          <Text style={styles.fieldVal}>{style.composition}</Text>

          <Text style={styles.fieldKey}>Audience signal</Text>
          <Text style={styles.fieldVal}>{style.audienceSignal}</Text>

          <Text style={styles.fieldKey}>Props</Text>
          <Text style={styles.fieldVal}>{style.props.join(' · ')}</Text>

          <Text style={styles.fieldKey}>Copy patterns</Text>
          <Text style={styles.fieldVal}>{style.copyPatterns.join(' · ')}</Text>

          <Text style={styles.fieldKey}>Negative patterns</Text>
          <Text style={styles.fieldVal}>{style.negativePatterns.join(' · ')}</Text>

          <Text style={styles.fieldKey}>Evidence</Text>
          {style.evidence.map((e, i) => (
            <Text key={i} style={styles.small}>
              #{e.imageIdx} — {e.claim}
            </Text>
          ))}

          <PageFooter />
        </Page>
      )}

      {/* Concept Briefs (one per page) */}
      {concepts.map((c) => (
        <Page key={c._id} size="A4" style={styles.page}>
          <PageHeader subtitle={`Concept ${c.position} · ${angleNameByConceptId[c._id] || ''}`} />
          <Text style={styles.h2}>
            Concept {c.position}: {angleNameByConceptId[c._id] || ''}
          </Text>
          <Text style={styles.lede}>{c.themeStatement}</Text>

          <Text style={styles.fieldKey}>Strategic rationale</Text>
          <Text style={styles.fieldVal}>{c.strategicRationale}</Text>

          <Text style={styles.fieldKey}>Color story</Text>
          <View style={styles.swatchRow}>
            {c.colorStory.map((p, i) => (
              <View key={i} style={[styles.swatch, { backgroundColor: p.hex }]} />
            ))}
          </View>
          <Text style={styles.fieldVal}>
            {c.colorStory.map((p) => `${p.hex} ${p.role} ${Math.round(p.ratio * 100)}%`).join(' · ')}
          </Text>

          <Text style={styles.fieldKey}>Typography</Text>
          <Text style={styles.fieldVal}>
            {c.typography.display} (display) · {c.typography.body} (body)
          </Text>

          <Text style={styles.fieldKey}>Shot recipe</Text>
          <Text style={styles.fieldVal}>
            {c.shotRecipe.shotType} · {c.shotRecipe.lighting} · {c.shotRecipe.composition} · {c.shotRecipe.lens} · {c.shotRecipe.setting}
          </Text>

          <Text style={styles.fieldKey}>Copy</Text>
          <Text style={styles.fieldVal}>
            {c.copy.headline}
            {c.copy.subhead ? ` — ${c.copy.subhead}` : ''} · CTA: {c.copy.cta}
          </Text>

          <Text style={styles.fieldKey}>Recommended prompt</Text>
          <Text style={styles.code}>{c.prompts.flux}</Text>

          <Text style={styles.fieldKey}>Negative prompt</Text>
          <Text style={styles.code}>{c.negativePrompt}</Text>

          <PageFooter />
        </Page>
      ))}

      {/* Prompt deck */}
      {deck && deck.cards.length > 0 && (
        <Page size="A4" style={styles.page} wrap>
          <PageHeader subtitle="Prompt deck" />
          <Text style={styles.h2}>Prompt deck</Text>
          <Text style={styles.small}>
            Copy any card into Midjourney, Flux Kontext, Nano Banana Pro, GPT-Image, or Ideogram.
          </Text>
          <View style={{ marginTop: 12 }}>
            {deck.cards.map((card, i) => (
              <View key={i} style={styles.card} wrap={false}>
                <Text style={styles.cardHead}>{card.heading}</Text>
                <Text style={styles.cardDesc}>{card.description}</Text>
                <Text style={styles.code}>{card.prompt}</Text>
                <Text style={styles.tag}>{card.tool}</Text>
              </View>
            ))}
          </View>
          <PageFooter />
        </Page>
      )}
    </Document>
  );
}
